version: 2
workflows:
  version: 2
  testing:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/php:7.0-cli-node

    working_directory: ~/repo
    steps:

      - checkout
      - run: sudo composer self-update
      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache: # special step to save the dependency cache with the `composer.lock` cache key template
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: if [ -f vendor/bin/phpunit ]; then vendor/bin/phpunit; fi